import type { Config } from 'tailwindcss';
import theme from './src/styles/tailwind.theme.json' with { type: 'json' };

/**
 * Tailwind theme.extend is generated by `pnpm tokens:build` from
 * packages/shared/src/design/tokens.ts. Never hand-edit tailwind.theme.json.
 */
const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: theme as Config['theme'],
  },
  plugins: [],
};

export default config;
