from enum import Enum


class CollectionName(str, Enum):
    ENG_WRITINGS = "englishWritings"
    WRITING_CRITERIA = "writingCriteria"
    MATH_PROBLEMS = "mathProblems"
    STUDENT_PROGRESS = "studentProgress"
    ANALYSIS_RESULTS = "analysisResults"
    CHATHISTORY = "chatHistory"


class ChatHistoryType(str, Enum):
    """
    **message**: human sent messages\n
    form: message generated by form submitting, usually along with 'payload'
    """

    TEXT = "text"
    FORM = "form"


class ChatHistoryRole(str, Enum):
    USER = "user"
    AI = "ai"


class ChatHistoryFormType(str, Enum):
    WRITING = "writing"
    MATH = "math"
