/**
 * Build CSS custom-property declarations + a Tailwind theme extension from
 * the KPDS token source at packages/shared/src/design/tokens.ts.
 *
 * Outputs:
 *   - apps/web/src/styles/tokens.css   (CSS vars scoped per [data-theme])
 *   - apps/web/src/styles/tailwind.theme.json (consumed by tailwind.config.ts)
 *
 * Run via `pnpm tokens:build`. Idempotent.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ageDeltas,
  childTokens,
  flattenAgeDelta,
  flattenTokens,
  parentTokens,
} from '@kidsprogress/shared';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const cssOut = resolve(repoRoot, 'apps/web/src/styles/tokens.css');
const themeOut = resolve(repoRoot, 'apps/web/src/styles/tailwind.theme.json');

function emitCss(): string {
  const parent = flattenTokens(parentTokens);
  const child = flattenTokens(childTokens);
  const younger = flattenAgeDelta(ageDeltas.younger);
  const older = flattenAgeDelta(ageDeltas.older);

  const block = (selector: string, vars: Record<string, string>): string => {
    const lines = Object.entries(vars)
      .map(([k, v]) => `  ${k}: ${v};`)
      .join('\n');
    return `${selector} {\n${lines}\n}`;
  };

  return [
    '/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit. */',
    '/* Source: packages/shared/src/design/tokens.ts */',
    '',
    block('[data-theme="parent"]', parent),
    '',
    block('[data-theme="child"]', child),
    '',
    block('[data-theme="child"][data-age="younger"]', younger),
    '',
    block('[data-theme="child"][data-age="older"]', older),
    '',
  ].join('\n');
}

/**
 * Tailwind theme.extend uses the CSS variables so utilities stay theme-aware.
 * Components write `className="bg-bg text-text"` and resolve at runtime.
 */
function emitTailwindTheme(): Record<string, unknown> {
  return {
    fontFamily: {
      sans: 'var(--kp-type-fontFamilySans)',
      display: 'var(--kp-type-fontFamilyDisplay)',
      mono: 'var(--kp-type-fontFamilyMono)',
    },
    fontSize: {
      '2xs': 'var(--kp-type-size2xs)',
      xs: 'var(--kp-type-sizeXs)',
      sm: 'var(--kp-type-sizeSm)',
      base: 'var(--kp-type-sizeBase)',
      lg: 'var(--kp-type-sizeLg)',
      xl: 'var(--kp-type-sizeXl)',
      '2xl': 'var(--kp-type-size2xl)',
      '3xl': 'var(--kp-type-size3xl)',
    },
    colors: {
      bg: 'var(--kp-color-bg)',
      surface: 'var(--kp-color-surface)',
      'surface-muted': 'var(--kp-color-surfaceMuted)',
      border: 'var(--kp-color-border)',
      text: 'var(--kp-color-text)',
      'text-muted': 'var(--kp-color-textMuted)',
      'text-subtle': 'var(--kp-color-textSubtle)',
      accent: 'var(--kp-color-accent)',
      'accent-fg': 'var(--kp-color-accentFg)',
      'accent-soft': 'var(--kp-color-accentSoft)',
      'accent-border': 'var(--kp-color-accentBorder)',
      success: 'var(--kp-color-success)',
      warning: 'var(--kp-color-warning)',
      danger: 'var(--kp-color-danger)',
      'focus-ring': 'var(--kp-color-focusRing)',
    },
    borderRadius: {
      sm: 'var(--kp-radius-sm)',
      md: 'var(--kp-radius-md)',
      lg: 'var(--kp-radius-lg)',
      xl: 'var(--kp-radius-xl)',
      '2xl': 'var(--kp-radius-2xl)',
      '3xl': 'var(--kp-radius-3xl)',
      full: 'var(--kp-radius-full)',
    },
    boxShadow: {
      sm: 'var(--kp-shadow-sm)',
      md: 'var(--kp-shadow-md)',
      lg: 'var(--kp-shadow-lg)',
      soft: 'var(--kp-shadow-soft)',
    },
    transitionDuration: {
      fast: 'var(--kp-motion-durationFast)',
      base: 'var(--kp-motion-durationBase)',
      slow: 'var(--kp-motion-durationSlow)',
    },
    transitionTimingFunction: {
      standard: 'var(--kp-motion-easingStandard)',
      enter: 'var(--kp-motion-easingEnter)',
      exit: 'var(--kp-motion-easingExit)',
      spring: 'var(--kp-motion-easingSpring)',
    },
    minHeight: {
      touch: 'var(--kp-spacing-touch)',
    },
    minWidth: {
      touch: 'var(--kp-spacing-touch)',
    },
    spacing: {
      'gutter-sm': 'var(--kp-spacing-gutterSm)',
      'gutter-md': 'var(--kp-spacing-gutterMd)',
      'gutter-lg': 'var(--kp-spacing-gutterLg)',
    },
    backgroundImage: {
      'kp-sunrise': 'var(--kp-gradient-sunrise)',
      'kp-forest': 'var(--kp-gradient-forest)',
      'kp-berry': 'var(--kp-gradient-berry)',
      'kp-ocean': 'var(--kp-gradient-ocean)',
      'kp-citrus': 'var(--kp-gradient-citrus)',
    },
  };
}

mkdirSync(dirname(cssOut), { recursive: true });
writeFileSync(cssOut, emitCss(), 'utf8');
writeFileSync(themeOut, JSON.stringify(emitTailwindTheme(), null, 2) + '\n', 'utf8');
console.log(`tokens.css → ${cssOut}`);
console.log(`tailwind.theme.json → ${themeOut}`);
